controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#accept_cookies:
 #   path: /
  #  controller: App\Controller\HomeController::acceptCookies