controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accept_cookies:
   path: /accept-cookies
   controller: App\Controller\CookieController::acceptCookies
   methods: POST